#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/leftdesk/leftdesk /usr/bin/leftdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/leftdesk.service ]; then
			rm /etc/systemd/system/leftdesk.service /usr/lib/systemd/system/leftdesk.service /usr/lib/systemd/user/leftdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/leftdesk/files/systemd/leftdesk.service /usr/lib/systemd/system/leftdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload leftdesk.service: Unit leftdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/leftdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/leftdesk.service
		fi
		systemctl daemon-reload
		systemctl enable leftdesk
		systemctl start leftdesk
	fi
fi
